BASHDOTDIR=$(dirname $(realpath "${BASH_SOURCE:-$0}"))
ASDF_DIR="$HOME/.local/asdf"
asdf_dir="$ASDF_DIR"
ASDF_DATA_DIR="$ASDF_DIR/data"
ASDF_CONFIG_FILE="$HOME/.config/asdf/asdfrc"
test ~/.bashrc && . ~/.bashrc
test "$BASHDOTDIR/bashrc" && . "$BASHDOTDIR/bashrc"
